import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
import {referenceGeometry,referenceEntity,projectReferenceData} from '../ui/atlas-reference-data.mjs';
import {referencePresetDocument,referenceSettingsCommands} from '../ui/atlas-reference-presets.mjs';
import {mountReferenceUi} from '../ui/atlas-reference-host.mjs';
import {createReferenceLorePort} from '../ui/atlas-reference-lore.mjs';
import {createDefaultSettingsV2,applySettingsCommand,settingsViewV2} from '../src/atlas-settings.ts';
const view=items=>({branchId:'main',revision:3,items});
const map={mapId:'world',name:'真实城市',kind:'city',containerLocationId:null,metersPerCell:2,points:[{entityId:'L',kind:'location',name:'学校',x:10,y:10},{entityId:'C',kind:'character',name:'艾琳',x:15,y:16,locationId:'L',isProtagonist:true}]};
const cat=[{entityId:'L',entityKind:'location',name:'学校',mapId:'world'},{entityId:'C',entityKind:'character',name:'艾琳',mapId:'world',locationId:'L',summary:'这是人物描述'}];
test('人物的实际子图点位优先于目录粗地图，地图计数和右栏对应画布',()=>{
 const d=projectReferenceData({mapView:view([{...map,points:map.points.filter(p=>p.kind==='location')},{mapId:'inside',name:'学校室内',kind:'site',containerLocationId:'L',points:[{entityId:'C',kind:'character',name:'艾琳',mapId:'inside',locationId:'L',x:5,y:5}]}]),catalogView:view(cat),viewMode:'author'});
 assert.equal(d.CAST[0].mapNodeId,'inside');assert.equal(d.ROOT.children[0].marks[0].id,'C');
});
test('子图计数与右栏包含本图对象，父图仍汇总后代；实体 ID 与地图 ID 不混用',()=>{
 const D={ROOT:{id:'world',children:[{id:'car-map',children:[{id:'cabin-map',children:[]}]}]},LOCATIONS:[{id:'cabin-location',mapId:'car-map'}],CAST:[{id:'C',state:'present',locationId:'cabin-location',mapNodeId:'cabin-map'}],ITEMS:[{id:'I',locationId:'cabin-location',mapNodeId:'cabin-map'}],MESSAGES:[],meta:{}};
 const code=readFileSync(new URL('../ui/atlas-reference/js/app.js',import.meta.url),'utf8');
 const ctx=vm.createContext({D,state:{nodeId:'cabin-map',viewMode:'author'}});vm.runInContext(code.slice(code.indexOf('function nodes('),code.indexOf('function message(')),ctx);
 assert.equal(ctx.sceneCast().length,1);assert.equal(ctx.sceneCast('world').length,1);assert.equal(ctx.sceneItems().length,1);
});
test('SQL 子地图按实际容器种类投影，site/interior 不冒充世界层级',()=>{
 for(const [sqlKind,containerKind,expected] of [['region','city','city'],['site','building','building'],['interior','room','room'],['site',null,'building'],['interior',null,'room']]){
  const g=referenceGeometry({...map,kind:sqlKind,containerLocationKind:containerKind});assert.equal(g.kind,expected);
 }
});
function projection(extra={}){return projectReferenceData({mapView:view([map]),catalogView:view(cat),viewMode:'author',...extra});}
test('原版接入：未知坐标不补零，实体 ID 与地图尺度保持来源',()=>{const g=referenceGeometry({...map,points:[...map.points,{entityId:'unknown',x:null,y:undefined}]});assert.equal(g.marks.length,2);assert.equal(g.marks[1].id,'C');assert.ok(Math.abs(g.metric*g.transform.scale-2)<1e-8);});
test('原版接入：描写不冒充行动，主角由正式地图确定',()=>{const d=projection();assert.equal(d.CAST[0].doing,'尚无行动记录');assert.equal(d.CAST[0].description,'这是人物描述');assert.equal(d.meta.protagonistId,'C');});
test('原版接入：扁平回执的成功、失败和时间准确',()=>{const d=projection({state:{receipts:[{receiptId:'R',status:'committed',summary:'已提交',recordedAt:'now'},{receiptId:'F',status:'rejected',summary:'失败'}]}});assert.equal(d.RECEIPTS[0].id,'R');assert.equal(d.RECEIPTS[0].ok,true);assert.equal(d.RECEIPTS[1].ok,false);assert.equal(d.RECEIPTS[0].t,'now');});
test('原版接入：人物在途不标成在场，手持物品来自真实 DTO',()=>{const d=referenceEntity({kind:'character',character:{id:'C',name:'艾琳',action_tendency:'前往学校',thought:'私密想法'},position:{kind:'in_transit'},heldItems:[{id:'I',name:'剑'}]});assert.equal(d.state,'away');assert.equal(d.doing,'前往学校');assert.deepEqual(d.carry,['剑']);});
test('原版接入：POV 未知位置不从目录恢复私密位置',()=>{const d=referenceEntity({kind:'character',character:{id:'C',name:'艾琳'},position:null},{locationId:'secret'});assert.equal(d.locationId,null);assert.equal(d.state,'unknown');assert.equal(d.mind,'尚无后台想法记录');});
test('原版接入：无坐标地点仍可通过目录关联真实子图',()=>{const d=projection({mapView:view([{...map,points:[]},{mapId:'room-map',name:'教室图',kind:'room',containerLocationId:'L',points:[]}])});assert.equal(d.ROOT.id,'world');assert.equal(d.ROOT.children[0].id,'room-map');assert.deepEqual(d.LOCATIONS[0].childMapIds,['room-map']);});
test('原版接入：河道、多边形和城墙直接接收空间参数',()=>{const g=referenceGeometry(map,{units:'meters',layout:{kind:'city',bounds:{x:0,y:0,w:100,h:80},river:{cx:50,amplitude:5,width:8,height:80},districts:[{id:'D',name:'学院区',polygon:[[0,0],[40,0],[40,30],[0,30]]}],wall:[[0,0],[100,0],[100,80]],roads:[]}});assert.equal(g.kind,'city');assert.equal(g.geo.districts.length,1);assert.equal(g.geo.river.length,41);assert.equal(g.geo.wallPoints.length,3);assert.ok(Math.abs(g.geo.riverWidth/g.transform.scale-8)<1e-8);});
test('原版接入：楼层房间、门、家具保留真实位置与大小',()=>{const g=referenceGeometry(map,{units:'meters',layout:{kind:'floor',bounds:{x:0,y:0,w:20,h:15},corridor:{x:0,y:6,w:20,h:3},rooms:[{id:'L',name:'教室',x:1,y:1,w:8,h:4}],doors:[{x:5,y:6,width:1}],groups:[{id:'G',bodies:[{type:'shelf',x:2,y:2,w:3,h:1}]}]}});assert.equal(g.kind,'floor');assert.equal(g.geo.rooms[0].id,'L');assert.equal(g.geo.furn[0].t,'shelf');assert.equal(g.marks[0].id,'L');assert.ok(Math.abs(g.geo.rooms[0].w/g.transform.scale-8)<1e-8);});
test('原版预设：默认使用正式 SQL 分段，保留启用和保护字段',()=>{const d=referencePresetDocument(settingsViewV2(createDefaultSettingsV2()));assert.ok(d.promptPresets[0].segments.length>1);assert.ok(d.promptPresets[0].segments.every(s=>s.content.length<=8000));});
const connection={id:'connection-native',name:'原版连接',provider:'openai-compatible',url:'https://example.com/v1',model:'model',temperature:0.7,maxTokens:8192,rememberKey:false,apiKey:'ephemeral-test-key'};
test('原版预设：新建明确声明 create，未勾选记住时不持久化 Key',()=>{const d=referencePresetDocument({});d.connections[0]=connection;d.assignments.advance.connectionId=connection.id;const cmd=referenceSettingsCommands(d,{}, {kind:'save',type:'connection',id:connection.id})[0];assert.equal(cmd.create,true);assert.equal(cmd.apiKeyMode,'clear');assert.equal(cmd.apiKey,undefined);const r=applySettingsCommand(createDefaultSettingsV2(),cmd);assert.ok(r.ok);assert.equal(r.settings.apiPresets[0].id,connection.id);assert.equal(r.settings.apiPresets[0].apiKey,'');});
test('原版预设：记住 Key 使用真实设置接口',()=>{const d=referencePresetDocument({});d.connections[0]={...connection,rememberKey:true};const cmd=referenceSettingsCommands(d,{}, {kind:'save',type:'connection',id:connection.id})[0];assert.equal(cmd.apiKeyMode,'replace');assert.equal(cmd.apiKey,connection.apiKey);});
test('原版预设：编辑基础字段保留已存高级连接参数',()=>{const old={id:connection.id,name:'old',apiKey:'',connectionMode:'profile',profileId:'profile',topP:0.3,timeoutMs:12345,bodyParams:'a: b',requestHeaders:'x: y',apiFormat:'claude'};const d=referencePresetDocument({apiPresets:[old]});d.connections[0].name='new';const cmd=referenceSettingsCommands(d,{apiPresets:[old]},{kind:'save',type:'connection',id:connection.id})[0];assert.equal(cmd.preset.profileId,'profile');assert.equal(cmd.preset.topP,0.3);assert.equal(cmd.preset.requestHeaders,'x: y');assert.equal(cmd.preset.apiFormat,'claude');});
test('原版预设：提示词上下文、保护字段、顺序和停用状态保留',()=>{const old={id:'P',name:'test',systemPrompt:'',contextTurnCount:7,segments:[{name:'main',role:'system',content:'a',enabled:false,mainSlot:1,deletable:false},{name:'b',role:'user',content:'b',enabled:true}]};const s={promptPresets:[old]},d=referencePresetDocument(s);const cmd=referenceSettingsCommands(d,s,{kind:'save',type:'prompt',id:'P'})[0];assert.equal(cmd.preset.contextTurnCount,7);assert.equal(cmd.preset.segments[0].mainSlot,1);assert.equal(cmd.preset.segments[0].deletable,false);assert.equal(cmd.preset.segments[0].enabled,false);});
test('原版预设：超过插件限制拒绝保存，不截断正文或段落',()=>{const d=referencePresetDocument({});d.promptPresets[0].segments[0].content='x'.repeat(8001);assert.throws(()=>referenceSettingsCommands(d,{}, {kind:'save',type:'prompt',id:d.promptPresets[0].id}),/8000/);d.promptPresets[0].segments=Array.from({length:17},()=>({content:'a'}));assert.throws(()=>referenceSettingsCommands(d,{}, {kind:'save',type:'prompt',id:d.promptPresets[0].id}),/16/);});
test('原版预设：原子批次后项失败时，不留下前项修改',()=>{const s=createDefaultSettingsV2(),d=referencePresetDocument({});d.connections[0]=connection;const cmd=referenceSettingsCommands(d,{}, {kind:'save',type:'connection',id:connection.id})[0],r=applySettingsCommand(s,{action:'batch',commands:[cmd,{action:'api.activate',id:'missing'}]});assert.equal(r.ok,false);assert.equal(r.settings,s);assert.equal(s.apiPresets.length,0);});
test('原版预设：新建 ID 碰撞被拒绝，普通更新不存在仍被拒绝',()=>{const s=createDefaultSettingsV2(),d=referencePresetDocument({});d.connections[0]=connection;const cmd=referenceSettingsCommands(d,{}, {kind:'save',type:'connection',id:connection.id})[0],r=applySettingsCommand(s,cmd);assert.equal(applySettingsCommand(r.settings,cmd).ok,false);assert.equal(applySettingsCommand(s,{...cmd,create:false}).ok,false);});
test('原版预设：异步保存失败后保留草稿，导出不包含 Key',async()=>{const window={crypto:{randomUUID:()=> 'unique'},TextEncoder},ctx=vm.createContext({window,TextEncoder,URL});vm.runInContext(readFileSync(new URL('../ui/atlas-reference/js/presets.js',import.meta.url),'utf8'),ctx);const initial=referencePresetDocument({});const store=window.AtlasPresetStore.create([],{storage:null,initialDocument:initial,onPersist:async()=>{throw Error('network failed');}});store.draft('prompt').segments[0].content='edited';await assert.rejects(store.save('prompt'),/network failed/);assert.equal(store.draft('prompt').segments[0].content,'edited');assert.notEqual(store.document.promptPresets[0].segments[0].content,'edited');assert.ok(!JSON.stringify(store.exportValue()).includes('apiKey'));});
function mount(options={}){
 const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'}),root=dom.window.document.getElementById('root');let state={chatId:'A',binding:options.unbound?null:{branchId:'main',enabled:options.bindingEnabled??true},stateData:{revision:3},receipts:[],panelOpen:true},context={chatId:'A',chatMetadata:{atlas:{database:{data:'A',sha256:'a'}}},extensionSettings:{atlas_world_sim:{sqlMode:options.enabled??true}}},calls=[],closes=0,loads=0,prefs={},settings=settingsViewV2(createDefaultSettingsV2());
 const sql={projectMapView:()=>null};
 const api={request:async(method,path,body)=>{if(path==='/sql/chat/ui-read'){calls.push(body);await options.delay?.(body);const data=body.kind==='map'?view([{...map,name:context.chatId}]):body.kind==='catalog'?view(cat):body.kind==='entity'?view([{kind:'character',character:{id:'C',name:context.chatId},position:{kind:'at_location'}}]):view([]);data.metadata={protagonistId:'C',snapshotSaved:!!context.chatMetadata.atlas?.database};return {status:200,body:{ok:true,data}};}if(method==='PUT'){const r=applySettingsCommand(settings,body);if(!r.ok)return {status:400,body:{ok:false,error:{message:r.message}}};settings={...settings,...r.settings};}return {status:200,body:{ok:true,data:settings}};},setRuntimeApiKeys:c=>calls.push({runtime:c.map(x=>({id:x.id,key:!!x.apiKey}))})};
 const core={getState:()=>state,setPage:()=>{},setPanelOpen:v=>{state.panelOpen=v;render();},setEnabled:async v=>{state.binding.enabled=v;calls.push({enabled:v});},manualAdvance:async()=>{calls.push({advance:true});if(options.advanceError)state.lastError=options.advanceError;},initializeWorld:async()=>false,retryLastCommit:async()=>{},refresh:async()=>{}};
 const render=mountReferenceUi({root,core,api,getContext:()=>context,settingsPort:{read:async()=>prefs,write:async(_,v)=>{prefs=v;}},loadSqlRuntime:async()=>{loads++;if(options.unavailable)throw Error('SQL_CORE_UNAVAILABLE');return sql;}}),bridge=root.firstChild.__atlasHost;
 return {root,core,render,bridge,calls,get loads(){return loads;},get closes(){return closes;},get prefs(){return prefs;},noSnapshot(){context.chatMetadata.atlas={};render();},switch(id){state={...state,chatId:id,lastError:null};context={...context,chatId:id,chatMetadata:{atlas:{database:{data:id,sha256:id}}}};render();},off(){context.extensionSettings.atlas_world_sim.sqlMode=false;render();}};
}
test('原版宿主：停用聊天可通过新入口重新启用，不写世界数据',async()=>{const m=mount({bindingEnabled:false});let b=await m.bridge.boot();assert.equal(b.data.meta.engine.enabled,false);await m.bridge.setEnabled(true);b=await m.bridge.boot();assert.equal(b.data.meta.engine.enabled,true);assert.ok(m.calls.some(c=>c.enabled===true));await m.bridge.advance();assert.ok(m.calls.some(c=>c.advance));await m.render.dispose();});
test('原版宿主：推演失败原因持续显示，切聊天不带入旧错误',async()=>{const m=mount({advanceError:'API_NOT_CONFIGURED：未配置连接'});await m.bridge.boot();await assert.rejects(m.bridge.advance(),/未配置连接/);let b=await m.bridge.boot();assert.match(b.data.meta.engine.error,/未配置连接/);assert.equal(b.data.meta.engine.busy,false);m.switch('B');b=await m.bridge.boot();assert.equal(b.data.meta.engine.error,null);await m.render.dispose();});
test('原版宿主：初始化未完成不能报告推演成功，未绑定也有诊断',async()=>{const m=mount({unbound:true});await m.bridge.boot();await assert.rejects(m.bridge.advance(),/初始化未完成/);const b=await m.bridge.boot();assert.match(b.data.DIAGNOSTICS[0].message,/初始化未完成/);await m.render.dispose();});
test('原版菜单：鼠标与键盘打开后让宿主关闭菜单，重复打开不留下遮挡',()=>{const dom=new JSDOM('<div id="extensionsMenu" style="display:block"></div>',{url:'http://localhost/'}),{document,KeyboardEvent}=dom.window;let open=false,closed=0,visible=true;document.documentElement.addEventListener('click',()=>{if(visible){visible=false;closed++;document.getElementById('extensionsMenu').style.display='none';}});const source=readFileSync(new URL('../index.js',import.meta.url),'utf8'),start=source.indexOf('function ensureAtlasMenuItem(core)'),end=source.indexOf('\nfunction removeMenuButton()',start);const ctx=vm.createContext({document,el:(tag,className,label)=>{const e=document.createElement(tag);if(className)e.className=className;if(label)e.textContent=label;return e;}});vm.runInContext(source.slice(start,end),ctx);const core={setPanelOpen:v=>{open=v;}};ctx.ensureAtlasMenuItem(core);const item=document.getElementById('atlas-menu-open');item.click();assert.equal(open,true);assert.equal(closed,1);assert.equal(visible,false);visible=true;open=false;item.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.equal(open,true);assert.equal(closed,2);ctx.ensureAtlasMenuItem(core);assert.equal(document.querySelectorAll('#atlas-menu-open').length,1);dom.window.close();});
test('原版宿主：关闭 SQL 时不加载运行时，不恢复旧世界',async()=>{const m=mount({enabled:false});const initial=await m.bridge.boot();assert.equal(m.loads,0);assert.equal(initial.data.CAST.length,0);assert.match(initial.data.meta.worldName,/暂停/);await m.render.dispose();});
test('原版宿主：读取引擎正式视图与同一修订，关闭 UI 不关闭引擎会话',async()=>{const m=mount();const result=await m.bridge.boot();assert.equal(result.data.CAST[0].name,'A');assert.ok(m.calls.some(q=>q.kind==='entity'));assert.ok(m.calls.filter(q=>q.kind!=='map').every(q=>q.revision===3));assert.ok(m.calls.some(q=>q.kind==='diagnostics'));assert.ok(!m.calls.some(q=>q.kind==='logs'));await m.render.dispose();assert.equal(m.root.children.length,0);});
test('原版宿主：首次推演尚无快照时读取内存库，不报读取失败也不要求保存',async()=>{const m=mount();m.noSnapshot();const b=await m.bridge.boot();assert.equal(b.data.CAST[0].name,'A');assert.equal(b.data.meta.snapshotSaved,false);assert.ok(!b.data.DIAGNOSTICS.some(x=>x.code==='REFERENCE_UI_READ_FAILED'));await m.render.dispose();});
test('原版回执：详细日志保留失败路径、分组和尝试；重复回执不标失败',()=>{const d=projection({state:{chatId:'A',retryableCommit:{chatId:'A'},receipts:[{chatId:'A',receiptId:'F',status:'failed',summary:'校验失败',retryable:true,errorCode:'TURN_FAILED',detail:{receipt:{groups:[{groupId:'G',status:'rejected',issues:[{code:'INVALID_FIELD',path:'$.data.kind',message:'种类错误'}]}]}}},{chatId:'A',receiptId:'D',status:'duplicate',summary:'重复回执'},{chatId:'B',receiptId:'secret',status:'failed',summary:'其他聊天'}]},logsView:view([{logId:'L',kind:'failed_turn',turnId:'F',status:'failed',receipt:{issues:[{path:'$.data.kind'}]},attempts:[{phase:'observe',status:'failed'}]}])});assert.equal(d.RECEIPTS.length,2);assert.equal(d.RECEIPTS[0].retryable,true);assert.equal(d.RECEIPTS[0].detail.receipt.groups[0].issues[0].path,'$.data.kind');assert.equal(d.RECEIPTS[0].logs[0].attempts[0].phase,'observe');assert.equal(d.RECEIPTS[1].ok,true);assert.equal(d.DIAGNOSTICS[0].receipt.issues[0].path,'$.data.kind');});
test('原版宿主：同分支同修订切聊天，晚到查询不覆盖新聊天',async()=>{let release;const blocked=new Promise(r=>{release=r;});let once=true;const m=mount({delay:q=>{if(q.kind==='map'&&once){once=false;return blocked;}}});const first=m.bridge.boot();await new Promise(r=>setTimeout(r,10));m.switch('B');release();await first;const current=await m.bridge.boot();assert.equal(current.data.CAST[0].name,'B');assert.ok(current.data.meta.scopeKey.includes('B'));await m.render.dispose();});
test('原版宿主：运行时不可用时显示具名错误，不混入旧 DTO',async()=>{const m=mount({unavailable:true});const result=await m.bridge.boot();assert.equal(result.data.CAST.length,0);assert.match(result.data.DIAGNOSTICS[0].message,/SQL_CORE_UNAVAILABLE/);await m.render.dispose();});
test('原版宿主：详情只查当前人物，视角切换重新取数',async()=>{const m=mount();await m.bridge.boot();await m.bridge.inspect('character','C');assert.equal(m.calls.at(-1).entityId,'C');await m.bridge.setViewMode('pov');assert.ok(m.calls.some(q=>q.kind==='map'&&q.viewMode==='pov'));await m.render.dispose();});
test('原版宿主：预设保存走真实原子接口，偏好保存不含 Key',async()=>{const m=mount();const initial=await m.bridge.boot(),doc=initial.presets;doc.connections[0]=connection;await m.bridge.persistPresets(doc,{kind:'save',type:'connection',id:connection.id});assert.ok(m.calls.some(q=>q.runtime));assert.ok(!JSON.stringify(m.prefs).includes(connection.apiKey));await m.render.dispose();});
test('原版世界书：读取与启停对应真实宿主条目，保留其他字段',async()=>{const ctx={chatId:'A',chatMetadata:{world_info:'Book'}},book={entries:{1:{comment:'学校',content:'real content',key:['学校'],disable:false,order:123}}};let saved;const port=createReferenceLorePort(()=>ctx,async()=>({loadWorldInfo:async()=>structuredClone(book),saveWorldInfo:async(_,value)=>{saved=value;}}));const rows=await port.read();assert.equal(rows[0].content,'real content');await port.toggle(rows[0].id);assert.equal(saved.entries[1].disable,true);assert.equal(saved.entries[1].order,123);});
test('原版世界书：晚到读结果不带进切换后的聊天',async()=>{let ctx={chatId:'A',chatMetadata:{world_info:'Book'}},release;const pending=new Promise(r=>{release=r;}),port=createReferenceLorePort(()=>ctx,async()=>({loadWorldInfo:async()=>{await pending;return {entries:{1:{content:'private A'}}};}}));const read=port.read();await new Promise(r=>setTimeout(r,0));ctx={chatId:'B',chatMetadata:{}};release();assert.deepEqual(await read,[]);});
test('原版行程：概览和已保存布局都按真实米格比例转换路线，不伪造未知进度',()=>{const d=projection({projectOverview:()=>({scene:{units:'meters',layout:{kind:'overview',bounds:{x:0,y:0,w:40,h:40},pins:[]}}}),flowView:view([{flowId:'J',kind:'journey',moverEntityId:'C',mapId:'world',progress:null,path:{units:'cells',points:[{x:0,y:0},{x:10,y:5},{x:20,y:20}]}}])});const edge=d.JOURNEYS.world[0];assert.deepEqual(edge.via,edge.points[1]);assert.equal(edge.entityId,'C');assert.equal(edge.progress,null);assert.ok(Math.abs(edge.to[0]-280)<1e-8);});
test('原版行程：未标定的格路线不能假定一格一米画到米制布局上',()=>{const d=projection({mapView:view([{...map,metersPerCell:null}]),projectOverview:()=>({scene:{units:'meters',layout:{kind:'overview',bounds:{x:0,y:0,w:40,h:40},pins:[]}}}),flowView:view([{flowId:'J',kind:'journey',mapId:'world',path:{units:'cells',points:[{x:0,y:0},{x:10,y:5}]}}])});assert.deepEqual(d.JOURNEYS,{});});
