import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const require = createRequire(join(root, 'package.json'));
const dir = join(root, 'artifacts/map-lab'); mkdirSync(dir, { recursive: true });
const result = await build({ entryPoints: [join(root, 'tools/map-lab/app.mjs')], bundle: true,
  write: false, target: 'es2022', charset: 'utf8', logLevel: 'silent',
  // Top-level await keeps the markercluster plugin behind window.L initialization.
  banner: { js: '(async () => {' }, footer: { js: '})();' }, format: 'esm' });
const leaflet = readFileSync(require.resolve('leaflet/dist/leaflet.css'), 'utf8').replace(/url\([^)]*\)/g, 'none');
const licenses = ['leaflet/LICENSE', 'leaflet.markercluster/MIT-LICENCE.txt'].map(path => readFileSync(require.resolve(path), 'utf8')).join('\n\n');
const css = `html,body{margin:0;height:100%;font:14px system-ui;color:#244845;background:#f4f1e9}body{display:flex;flex-direction:column}header{display:flex;align-items:center;gap:12px;padding:14px 20px;background:#163332;color:#f0e9d7}header strong{letter-spacing:2px}header span{font-size:12px;color:#becdca}nav{display:flex;gap:8px;padding:10px 16px;flex-wrap:wrap;border-bottom:1px solid #d9d4c8}button,select{font:inherit;color:#254d49;background:#faf8f2;border:1px solid #c9c2b0;border-radius:5px;padding:6px 10px;cursor:pointer}button:hover{background:#e2eeea}#crumbs{display:flex;align-items:center;flex-wrap:wrap;gap:5px}#map{flex:1;min-height:260px;background:#eeeee6}footer{padding:9px 16px;font-size:12px;color:#58726e}.lab-grid{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:350}.lab-grid path{fill:none;stroke:#6b9e98;stroke-width:1}.lab-grid .minor{opacity:.14}.lab-grid .major{opacity:.24}.lab-icon{width:0!important;height:0!important}.lab-pin,.lab-cluster{display:inline-block;transform:translate(-50%,-50%);border:1px solid #6b9189;border-radius:5px;padding:6px 10px;white-space:nowrap;background:#fcfaf4;color:#234d48;box-shadow:0 2px 5px #234d4820}.lab-pin--character{border-radius:50%;padding:0;width:26px;height:26px;text-align:center;line-height:26px;background:#275e58;color:#fff}.lab-cluster{font-weight:600;background:#dcebe4;border:2px solid #729e91}.lab-label{pointer-events:none}.lab-fixture{display:inline-block;transform:translate(-50%,-50%);white-space:nowrap;color:#446e65;font-size:11px;background:#f7f6efb0;padding:2px 4px;border-radius:3px}.lab-members{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;max-height:190px;overflow:auto;margin-top:8px}.lab-members button{font-size:12px;padding:5px}.leaflet-popup-content{margin:14px}.leaflet-popup-content p{margin:8px 0}.leaflet-control-zoom a{color:#315d56}@media(max-width:600px){header{padding:10px 12px}header span{display:none}nav{padding:8px;gap:6px}button,select{font-size:12px;padding:5px 7px}}`;
const script = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
writeFileSync(join(dir, 'index.html'), `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Atlas 地图交互验证</title><style>${leaflet}\n${css}</style><body><header><strong>ATLAS</strong><span>地图交互验证 · 使用现有三表投影</span></header><nav><select id="scenario" aria-label="验收场景"><option value="school">12×8 教室</option><option value="building">建筑区域</option><option value="crowd">50 人重叠</option></select><button id="home">世界图</button><button id="locate">📍 当前教室</button><div id="crumbs"></div></nav><main id="map"></main><footer id="status"></footer><script>${script}</script><script type="text/plain" id="third-party-licenses">${licenses.replace(/</g, '&lt;')}</script></body></html>`);
console.log('Built artifacts/map-lab/index.html (offline, no chat/API calls)');
